# File of settings and constants

NUM_USERS = 100
NUM_ITEMS_PER_ITER = 10
TIMESTEPS = 100
NUM_STARTUP_ITER = 10
# users are presented NUM_ITEMS_PER_ITER items per iteration drawn from NUM_ITEMS_PER_ITER * CONSTANT items
CONSTANT = 10

NUM_ITEMS = TIMESTEPS * NUM_ITEMS_PER_ITER * CONSTANT